- src: chrismeyersfsu.provision_docker
  name: provision_docker

- src: manala.git
- src: manala.ohmyzsh
- src: manala.zsh
- src: mmacia.ohmyzsh
- src: bdellegrazie.ca-certificates
- src: manala.apt
- src: manala.shorewall
- src: https://github.com/EugenMayer/ansible-shorewall
  name: eugenmayer.shorewall