---

#- name: Bring up docker containers for docker connection inventory iface
#  hosts: localhost
#  roles:
#    - role: provision_docker
#      provision_docker_image: registry.kw.kontextwork.com/ansible:testjessie
#      provision_docker_privileged: true,
#      provision_docker_inventory_group: "{{ groups['robots'] }}"
#      provision_docker_use_docker_connection: true

# start our test container
- hosts: localhost
  tasks:
    - name: Create container
      docker_container:
        name: ansibletestserver
        image: eugenmayer/docker-image-ansible

# those would be the test roles whatever we do
- hosts: ansibletestserver
  roles:
    - common

#
## start our test container
#- hosts: localhost
#  tasks:
#    - name: Remove container
#      docker_container:
#        name: ansibletestserver
#        state: absent

